name: caching_excellence_riverpod
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # network
  dio: ^5.2.1+1

  # state management
  flutter_riverpod: ^2.3.6

  # utils
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
